# fly.toml app configuration file generated for frovollseter-api on 2026-04-25T13:44:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frovollseter-api'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ASPNETCORE_URLS = 'http://+:8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[metrics]]
  port = 9091
  path = '/metrics'
